"use client";

import {
  Check,
  CheckSquare2,
  FileText,
  Film,
  Grid2X2,
  ImagePlus,
  Link as LinkIcon,
  List,
  Loader2,
  Play,
  RotateCcw,
  Search,
  Square,
  Trash2,
  UploadCloud,
  X,
} from "lucide-react";
import * as React from "react";
import type { IconType } from "react-icons/lib";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { Ecodrix } from "@ecodrix/erix-api";
import { useErixClient } from "@/context/ErixProvider";

export interface ImageVariants {
  thumb: string;
  medium: string;
  full: string;
  raw: string;
}

export interface ImageFormat {
  url: string;
  name?: string;
  type?: string;
  fileName?: string;
  key?: string;
  lastModified?: Date;
  size?: number;
  thumbnail?: string;
  used?: boolean;
  usageCount?: number;
  /**
   * Cloudflare /cdn-cgi/image/ variant URLs generated by the backend.
   * Use these instead of `url` for display — they are device-appropriate
   * and served in the best format (WebP/AVIF) for the requesting browser.
   *
   * - thumb  → 150px, for thumbnails & library grid
   * - medium → 600px, for panels & modals
   * - full   → 1200px, for hero / lightbox
   * - raw    → original CDN URL, no transformation
   */
  variants?: ImageVariants;
  usagePoints?: {
    category?: number;
    productFeatured?: number;
    productGallery?: number;
  };
}

interface ImagePickerNativeProps {
  onInsert?: (url: ImageFormat[]) => void;
  selected?: ImageFormat[];
  aspectRatio?: "square" | "portrait" | "landscape" | "free";
  maxSize?: number;
  multiple?: boolean;
  open?: boolean;
  setOpen?: (value: boolean) => void;
  trigger?: boolean;
  className?: string;
  selectedImages?: ImageFormat[];
  icon?: IconType;
  size?: string;
  folder?: string;
  apiUrl?: string;
  apiKey?: string;
  clientCode?: string;
  variant?: "richtext" | "casual";
  children?: React.ReactNode;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

const formatBytes = (bytes: number | undefined, decimals = 1) => {
  if (!bytes || !+bytes) return "0 B";
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ["B", "KB", "MB", "GB", "TB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / k ** i).toFixed(dm))} ${sizes[i]}`;
};

const getDisplayName = (src: ImageFormat) => {
  let name = src.fileName || "";
  if (!name && src.url) {
    name = decodeURIComponent(src.url.split("/").pop() || "");
  }
  if (!name) return "";
  // Strip trailing timestamp appended by storage (e.g. somefile_1712046892123.jpg)
  name = name.replace(/[_-]\d{13,}(\.[^.]+)?$/, (_, p1) => p1 || "");
  const dotIdx = name.lastIndexOf(".");
  const nameWithoutExt = dotIdx > 0 ? name.slice(0, dotIdx) : name;
  const ext = dotIdx > 0 ? name.slice(dotIdx + 1) : "";
  const cleanName = nameWithoutExt.replace(/[-_]/g, " ").trim();
  return ext ? `${cleanName}.${ext}` : cleanName;
};

/**
 * Checks whether a backend media item is an image.
 * Checks categorical type first (backend now returns "image" | "video" | "audio" | "document"),
 * then falls back to MIME type and URL extension for legacy items.
 */
const isImage = (src: ImageFormat) => {
  if (src.type === "image") return true; // backend categorical type
  if (src.type?.startsWith("image/")) return true; // legacy MIME type
  if (src.url?.match(/\.(jpe?g|png|gif|webp|avif|svg)$/i)) return true;
  if (src.fileName?.match(/\.(jpe?g|png|gif|webp|avif|svg)$/i)) return true;
  return false;
};

const isPdf = (src: ImageFormat) => {
  if (src.type === "document") return true; // categorical — all docs treated as pdf filter
  if (src.type === "application/pdf") return true; // legacy MIME type
  if (src.url?.match(/\.pdf$/i)) return true;
  if (src.fileName?.match(/\.pdf$/i)) return true;
  return false;
};

const isVideo = (src: ImageFormat) => {
  if (src.type === "video") return true; // backend categorical type
  if (src.type?.startsWith("video/")) return true; // legacy MIME type
  if (src.url?.match(/\.(mp4|webm|ogg|mov)$/i)) return true;
  if (src.fileName?.match(/\.(mp4|webm|ogg|mov)$/i)) return true;
  return false;
};

const isAudio = (src: ImageFormat) => {
  if (src.type === "audio") return true;
  if (src.type?.startsWith("audio/")) return true;
  if (src.url?.match(/\.(mp3|ogg|wav|aac|flac|m4a|opus)$/i)) return true;
  if (src.fileName?.match(/\.(mp3|ogg|wav|aac|flac|m4a|opus)$/i)) return true;
  return false;
};

// ─── Skeleton Cards ──────────────────────────────────────────────────────────

const GridSkeleton = () => (
  <div className="erix-rounded-lg erix-overflow-hidden erix-border erix-border-border/50 erix-animate-pulse">
    <div className="erix-aspect-square erix-bg-muted" />
    <div className="erix-px-2 erix-py-1.5 erix-bg-muted/40">
      <div className="erix-h-2 erix-w-3/4 erix-rounded erix-bg-muted-foreground/20" />
    </div>
  </div>
);

const ListSkeleton = () => (
  <div className="erix-flex erix-items-center erix-gap-3 erix-p-2 erix-rounded-lg erix-border erix-border-border/50 erix-animate-pulse">
    <div className="erix-h-12 erix-w-12 erix-rounded-md erix-bg-muted erix-shrink-0" />
    <div className="erix-flex-1 erix-space-y-1.5">
      <div className="erix-h-2.5 erix-w-2/3 erix-rounded erix-bg-muted-foreground/20" />
      <div className="erix-h-2 erix-w-1/3 erix-rounded erix-bg-muted-foreground/10" />
    </div>
  </div>
);

// ─── Media Thumbnail ─────────────────────────────────────────────────────────

const MediaThumb = ({
  src,
  index,
  mode,
}: {
  src: ImageFormat;
  index: number;
  mode: "grid" | "list";
}) => {
  const cls =
    mode === "grid"
      ? "aspect-square w-full"
      : "h-12 w-12 shrink-0 rounded-md overflow-hidden";

  if (isPdf(src)) {
    return (
      <div
        className={cn(
          "relative flex items-center justify-center bg-red-50 dark:bg-red-950/30",
          cls,
          mode === "grid" && "rounded-none",
        )}
      >
        <FileText className="erix-h-7 erix-w-7 erix-text-red-400" />
        <span className="erix-absolute erix-bottom-1.5 erix-right-1.5 erix-rounded erix-bg-red-500 erix-px-1 erix-py-0.5 erix-text-[8px] erix-font-bold erix-uppercase erix-tracking-widest erix-text-white erix-shadow">
          PDF
        </span>
      </div>
    );
  }

  if (isVideo(src)) {
    return (
      <div
        className={cn(
          "relative overflow-hidden bg-black",
          cls,
          mode === "grid" && "rounded-none",
        )}
      >
        <video
          src={src.url}
          className="erix-h-full erix-w-full erix-object-cover erix-opacity-80"
          muted
          onMouseOver={(e) => e.currentTarget.play()}
          onMouseOut={(e) => {
            e.currentTarget.pause();
            e.currentTarget.currentTime = 0;
          }}
        />
        <div className="erix-absolute erix-inset-0 erix-flex erix-items-center erix-justify-center">
          <div className="erix-rounded-full erix-bg-black/50 erix-p-1.5 erix-backdrop-blur-sm">
            <Play className="erix-h-3 erix-w-3 erix-fill-white erix-text-white" />
          </div>
        </div>
        <span className="erix-absolute erix-bottom-1 erix-left-1 erix-flex erix-items-center erix-gap-0.5 erix-rounded erix-bg-black/60 erix-px-1 erix-py-0.5 erix-backdrop-blur-sm">
          <Film className="erix-h-2.5 erix-w-2.5 erix-text-white" />
          <span className="erix-text-[8px] erix-font-bold erix-uppercase erix-text-white">
            VID
          </span>
        </span>
      </div>
    );
  }

  return (
    <div
      className={cn(
        "relative overflow-hidden bg-muted",
        cls,
        mode === "grid" && "rounded-none",
      )}
    >
      <img
        width={mode === "grid" ? 200 : 48}
        height={mode === "grid" ? 200 : 48}
        loading="lazy"
        src={
          // Prefer Cloudflare thumb variant for grid/list display.
          // Falls back to raw url if variants are not yet available
          // (e.g. non-image files, or legacy uploads pre-dating variants).
          mode === "grid"
            ? (src.variants?.thumb ?? src.url ?? "/placeholder.png")
            : (src.variants?.thumb ?? src.url ?? "/placeholder.png")
        }
        alt={src.name || `Media ${index}`}
        className="erix-h-full erix-w-full erix-object-cover erix-transition-transform erix-duration-200 group-hover:erix-scale-[1.04]"
      />
    </div>
  );
};

// ─── Main Component ───────────────────────────────────────────────────────────

export const ImagePickerNative: React.FC<ImagePickerNativeProps> = ({
  onInsert,
  selected,
  maxSize = 50,
  multiple = false,
  open,
  setOpen,
  trigger = false,
  className,
  selectedImages: externalSelectedImages,
  icon: Icon = ImagePlus,
  size = "size-10",
  folder = "profile",
  apiUrl,
  apiKey,
  clientCode,
  variant = "casual",
  children,
}) => {
  const [internalOpen, setInternalOpen] = React.useState(false);
  const [externalUrl, setExternalUrl] = React.useState("");
  const [isUploading, setIsUploading] = React.useState(false);

  // Initialize SDK client: Prefer context, but fallback to local instance for standalone props
  const contextSdk = React.useRef<Ecodrix | null>(null);
  try {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    contextSdk.current = useErixClient();
  } catch (_) {
    // Component used outside of ErixProvider
  }

  const sdk = React.useMemo(() => {
    if (contextSdk.current && !apiUrl && !apiKey) return contextSdk.current;
    if (!apiUrl || !apiKey) return contextSdk.current || null;

    return new Ecodrix({
      baseUrl: apiUrl,
      apiKey: apiKey,
      clientCode: clientCode || "default",
    });
  }, [contextSdk, apiUrl, apiKey, clientCode]);

  const isOpen = open !== undefined ? open : internalOpen;
  const handleOpenChange = (val: boolean) => {
    if (setOpen) setOpen(val);
    setInternalOpen(val);
  };
  const [uploadingCount, setUploadingCount] = React.useState(0);
  const [deletingKeys, setDeletingKeys] = React.useState<string[]>([]);
  const [images, setImages] = React.useState<ImageFormat[]>([]);
  const [loadingImages, setLoadingImages] = React.useState(true);
  const [uploadProgress, setUploadProgress] = React.useState(0);
  const [searchQuery, setSearchQuery] = React.useState("");
  const [viewMode, setViewMode] = React.useState<"grid" | "list">("grid");
  const [dragActive, setDragActive] = React.useState(false);
  const [filterType, setFilterType] = React.useState<
    "all" | "image" | "video" | "pdf"
  >("all");
  const [selectedImages, setSelectedImage] = React.useState<ImageFormat[]>();
  const [isOverQuota, setIsOverQuota] = React.useState(false);

  // Sync external selection and reset state on close
  React.useEffect(() => {
    if (open) {
      setSelectedImage(selected ? [...selected] : []);
    } else {
      setSelectedImage([]);
      setSearchQuery("");
      setFilterType("all");
    }
  }, [selected, open]);

  React.useEffect(() => {
    if (open && externalSelectedImages) {
      setSelectedImage([...externalSelectedImages]);
    }
  }, [externalSelectedImages, open]);

  // Fetch library
  const fetchImages = React.useCallback(async () => {
    try {
      setLoadingImages(true);
      if (!sdk) {
        console.warn("[MediaPicker] SDK client not initialized.");
        setLoadingImages(false);
        return;
      }
      // Guard: if clientCode is missing or still at the placeholder default,
      // the backend will return 'Client not found'. Surface a clear no-op.
      const resolvedClientCode =
        clientCode && clientCode !== "default" ? clientCode : null;
      if (!resolvedClientCode) {
        console.warn(
          "[MediaPicker] No valid clientCode — media library requires a real clientCode. " +
          "Pass it via the 'clientCode' prop or configure it in <ErixProvider>.",
        );
        setLoadingImages(false);
        return;
      }

      const res = await sdk.media.list(folder, { q: searchQuery });
      const images = (res as any).data?.images ?? [];
      const overQuota = !!(res as any).data?.isOverQuota;

      setImages(images);
      setIsOverQuota(overQuota);
    } catch (err: any) {
      console.error("[MediaPicker] Fetch Error:", err);
    } finally {
      setLoadingImages(false);
    }
  }, [sdk, folder, searchQuery, clientCode]);

  React.useEffect(() => {
    fetchImages();
  }, [fetchImages]);

  // Combined filtering (Client-side Search & Types)
  const filteredImages = React.useMemo(() => {
    return images.filter((img) => {
      // Name Search
      if (searchQuery) {
        const displayName = getDisplayName(img).toLowerCase();
        if (!displayName.includes(searchQuery.toLowerCase())) return false;
      }

      // Type Filter
      if (filterType === "all") return true;
      if (filterType === "image") return isImage(img);
      if (filterType === "video") return isVideo(img);
      if (filterType === "pdf") return isPdf(img);
      return true;
    });
  }, [images, filterType, searchQuery]);

  // Select all toggle
  const handleSelectAll = () => {
    if ((selectedImages?.length ?? 0) >= images.length && images.length > 0) {
      setSelectedImage([]);
    } else {
      setSelectedImage([...images]);
    }
  };

  // Upload
  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    if (files.length === 0 || isOverQuota) return;

    const validFiles = files.filter((file) => {
      if (file.size > maxSize * 1024 * 1024) {
        alert(`${file.name} exceeds the ${maxSize}MB limit.`);
        return false;
      }
      const ok = ["image/", "video/", "application/pdf"].some((t) =>
        file.type.startsWith(t),
      );
      if (!ok) {
        alert(`${file.name}: unsupported format.`);
        return false;
      }
      return true;
    });

    if (validFiles.length === 0) return;

    setUploadingCount(validFiles.length);
    setIsUploading(true);
    setUploadProgress(10);

    try {
      if (!sdk) throw new Error("SDK not initialized");

      for (const file of validFiles) {
        setUploadingCount((prev) => prev + 1);
        const { data: result } = await sdk.media.upload(file, {
          folder,
          filename: file.name,
          contentType: file.type,
        });

        // result is the confirmed file meta
        setImages((prev) => [result, ...prev]);

        if (multiple) {
          setSelectedImage((prev) => [...(prev || []), result]);
        } else {
          setSelectedImage([result]);
        }
        setUploadingCount((prev) => Math.max(0, prev - 1));
      }
    } catch (err: any) {
      console.error("[MediaPicker] Upload Error:", err);
      alert(err.message || "Upload failed");
    } finally {
      setIsUploading(false);
      setUploadingCount(0);
      setUploadProgress(0);
      // reset file input
      e.target.value = "";
    }
  };

  // Drag & drop
  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") setDragActive(true);
    if (e.type === "dragleave") setDragActive(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    const files = e.dataTransfer.files;
    if (files?.[0]) {
      handleUpload({
        target: { files },
      } as React.ChangeEvent<HTMLInputElement>);
    }
  };

  // Selection
  const handleSelectImage = (image: ImageFormat) => {
    if (multiple) {
      setSelectedImage((prev) =>
        prev?.some((item) => item.url === image.url)
          ? prev.filter((item) => item.url !== image.url)
          : [...(prev || []), image],
      );
    } else {
      setSelectedImage([image]);
    }
  };

  const isSelected = (src: ImageFormat) =>
    !!selectedImages?.find((i) => i?.url === src?.url);

  // Delete
  const handleDeleteMedia = async (e: React.MouseEvent, src: ImageFormat) => {
    e.stopPropagation();
    if (!src.key || !sdk) return alert("Cannot delete: missing media key or SDK.");
    if (!confirm("Permanently delete this file?")) return;

    try {
      setDeletingKeys((prev) => [...prev, src.key!]);
      await sdk.media.delete(src.key);
      setImages((prev) => prev.filter((img) => img.key !== src.key));
      setSelectedImage((prev) => prev?.filter((img) => img.key !== src.key));
    } catch (err: any) {
      console.error("[MediaPicker] Delete Error:", err);
      alert(err.message || "Delete failed");
    } finally {
      setDeletingKeys((prev) => prev.filter((key) => key !== src.key));
    }
  };

  const selCount = selectedImages?.length ?? 0;
  const allSelected = images.length > 0 && selCount === images.length;

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      {children ? (
        <DialogTrigger asChild>{children}</DialogTrigger>
      ) : trigger ? (
        <DialogTrigger asChild>
          <Button
            role="button"
            variant="dashed"
            size="sm"
            aria-label="Upload Image"
            className={cn(
              "erix-h-inherit erix-flex erix-h-full erix-w-full erix-cursor-pointer erix-items-center erix-justify-center erix-border erix-border-dashed focus-visible:erix-ring-0",
              className,
            )}
            pointer
          >
            <Icon className={cn(size, "erix-text-primary/70")} />
          </Button>
        </DialogTrigger>
      ) : null}

      <DialogContent className="erix-flex erix-max-h-[88vh] erix-flex-col erix-gap-0 erix-overflow-hidden erix-rounded-xl erix-p-0 erix-shadow-2xl sm:erix-max-w-[760px]">
        <Tabs
          defaultValue="library"
          className="erix-flex erix-flex-col erix-h-full"
        >
          {variant === "richtext" && (
            <div className="erix-px-5 erix-pt-4 erix-pb-0">
              <TabsList className="erix-bg-muted/50 erix-grid erix-grid-cols-2 erix-w-[280px]">
                <TabsTrigger value="library" className="erix-gap-2">
                  <ImagePlus className="erix-w-3.5 erix-h-3.5" /> Library
                </TabsTrigger>
                <TabsTrigger value="url" className="erix-gap-2">
                  <LinkIcon className="erix-w-3.5 erix-h-3.5" /> External URL
                </TabsTrigger>
              </TabsList>
            </div>
          )}

          <TabsContent
            value="library"
            className="erix-mt-0 erix-flex-1 erix-flex erix-flex-col erix-overflow-hidden erix-data-[state=inactive]:erix-hidden"
          >
            {/* ── Header ── */}
            <DialogHeader className="erix-border-b erix-border-border/60 erix-bg-background erix-px-5 erix-pt-4 erix-pb-3 erix-shrink-0">
              <div className="erix-flex erix-items-center erix-justify-between">
                <DialogTitle className="erix-text-base erix-font-semibold erix-tracking-tight">
                  Media Library
                </DialogTitle>
                <div className="erix-flex erix-items-center erix-gap-1.5">
                  {/* Select All (multi mode only) */}
                  {multiple && images.length > 0 && (
                    <button
                      onClick={handleSelectAll}
                      className="erix-flex erix-items-center erix-gap-1.5 erix-rounded-md erix-border erix-border-border erix-px-2.5 erix-py-1 erix-text-xs erix-font-medium erix-text-muted-foreground erix-transition-colors hover:erix-bg-accent hover:erix-text-foreground"
                    >
                      {allSelected ? (
                        <CheckSquare2 className="erix-h-3.5 erix-w-3.5 erix-text-primary" />
                      ) : (
                        <Square className="erix-h-3.5 erix-w-3.5" />
                      )}
                      {allSelected ? "Deselect All" : "Select All"}
                    </button>
                  )}

                  {/* Refresh */}
                  <button
                    onClick={fetchImages}
                    disabled={loadingImages}
                    className="erix-flex erix-h-8 erix-w-8 erix-items-center erix-justify-center erix-rounded-md erix-border erix-border-border erix-text-muted-foreground erix-transition-colors hover:erix-bg-accent hover:erix-text-foreground disabled:erix-opacity-50"
                    title="Refresh"
                  >
                    {loadingImages ? (
                      <Loader2 className="erix-h-4 erix-w-4 erix-animate-spin" />
                    ) : (
                      <RotateCcw className="erix-h-4 erix-w-4" />
                    )}
                  </button>

                  {/* View toggle */}
                  <div className="erix-flex erix-items-center erix-rounded-md erix-h-8 erix-border erix-border-border erix-bg-muted/40 erix-p-0.5 erix-mr-5">
                    <button
                      onClick={() => setViewMode("grid")}
                      className={cn(
                        "rounded px-2 py-1.5 transition-colors",
                        viewMode === "grid"
                          ? "bg-background text-foreground shadow-sm"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="Grid view"
                    >
                      <Grid2X2 className="erix-h-3.5 erix-w-3.5" />
                    </button>
                    <button
                      onClick={() => setViewMode("list")}
                      className={cn(
                        "rounded px-2 py-1.5 transition-colors",
                        viewMode === "list"
                          ? "bg-background text-foreground shadow-sm"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="List view"
                    >
                      <List className="erix-h-3.5 erix-w-3.5" />
                    </button>
                  </div>
                </div>
              </div>

              {/* Search & Filters */}
              <div className="erix-mt-1 erix-flex erix-items-center erix-gap-2">
                <div className="erix-relative erix-flex-1">
                  <Search className="erix-pointer-events-none erix-absolute erix-top-1/2 erix-left-2.5 erix-h-3.5 erix-w-3.5 erix--translate-y-1/2 erix-text-muted-foreground" />
                  <input
                    type="search"
                    placeholder="Search files…"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="erix-h-8 erix-w-full erix-rounded-md erix-border erix-border-border erix-bg-background erix-pl-8 erix-pr-3 erix-text-sm placeholder:erix-text-muted-foreground/60 focus:erix-border-primary focus:erix-outline-none focus:erix-ring-1 focus:erix-ring-primary/30"
                  />
                </div>

                <Select
                  value={filterType}
                  onValueChange={(val: "all" | "image" | "video" | "pdf") =>
                    setFilterType(val)
                  }
                >
                  <SelectTrigger
                    size="sm"
                    className="erix-w-auto erix-text-[11px] erix-font-medium erix-transition-colors hover:erix-bg-muted/60"
                  >
                    <SelectValue placeholder="Format" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all" className="erix-text-xs">
                      All Formats
                    </SelectItem>
                    <SelectItem value="image" className="erix-text-xs">
                      Images
                    </SelectItem>
                    <SelectItem value="video" className="erix-text-xs">
                      Videos
                    </SelectItem>
                    <SelectItem value="pdf" className="erix-text-xs">
                      PDFs
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </DialogHeader>

            {/* ── Scrollable Body ── */}
            <div className="erix-flex-1 erix-overflow-y-auto erix-bg-muted/20 erix-p-4 erix-space-y-4 erix-scrollbar-thin erix-scrollbar-thumb-border erix-scrollbar-track-transparent">
              {/* Upload Zone */}
              <div
                role="button"
                onDragEnter={handleDrag}
                onDragLeave={handleDrag}
                onDragOver={handleDrag}
                onDrop={handleDrop}
                className={cn(
                  "relative flex items-center gap-4 rounded-xl border-2 border-dashed px-5 py-4 transition-all duration-200",
                  dragActive
                    ? "border-primary bg-primary/5 scale-[1.01]"
                    : "border-border/70 bg-background hover:border-primary/50 hover:bg-primary/2",
                  (isUploading || isOverQuota) &&
                    "pointer-events-none opacity-90",
                )}
              >
                {isOverQuota ? (
                  <div className="erix-flex erix-w-full erix-items-center erix-gap-4 erix-py-2 erix-opacity-80">
                    <div className="erix-flex erix-h-10 erix-w-10 erix-shrink-0 erix-items-center erix-justify-center erix-rounded-full erix-bg-destructive/10 erix-border erix-border-destructive/20 erix-text-destructive">
                      <RotateCcw className="erix-h-5 erix-w-5" />
                    </div>
                    <div>
                      <p className="erix-text-sm erix-font-semibold erix-text-destructive">
                        Storage Limit Reached
                      </p>
                      <p className="erix-text-xs erix-text-muted-foreground erix-mt-0.5">
                        Clear some space or upgrade your plan to upload more
                        files
                      </p>
                    </div>
                  </div>
                ) : isUploading ? (
                  <div className="erix-flex erix-w-full erix-items-center erix-gap-4">
                    <div className="erix-flex erix-h-10 erix-w-10 erix-shrink-0 erix-items-center erix-justify-center erix-rounded-full erix-bg-primary/10">
                      <Loader2 className="erix-h-5 erix-w-5 erix-animate-spin erix-text-primary" />
                    </div>
                    <div className="erix-flex-1 erix-min-w-0">
                      <p className="erix-text-sm erix-font-medium">
                        Uploading {uploadingCount} file
                        {uploadingCount > 1 ? "s" : ""}…
                      </p>
                      <div className="erix-mt-1.5 erix-h-1.5 erix-w-full erix-overflow-hidden erix-rounded-full erix-bg-muted">
                        <div
                          className="erix-h-full erix-rounded-full erix-bg-primary erix-transition-all erix-duration-300"
                          style={{ width: `${uploadProgress || 30}%` }}
                        />
                      </div>
                    </div>
                    <span className="erix-text-xs erix-tabular-nums erix-text-muted-foreground">
                      {uploadProgress}%
                    </span>
                  </div>
                ) : (
                  <>
                    <div className="erix-flex erix-h-10 erix-w-10 erix-shrink-0 erix-items-center erix-justify-center erix-rounded-full erix-bg-primary/8 erix-border erix-border-primary/20">
                      <UploadCloud className="erix-h-5 erix-w-5 erix-text-primary" />
                    </div>
                    <div className="erix-min-w-0">
                      <p className="erix-text-sm erix-font-medium erix-leading-snug">
                        Drop files or{" "}
                        <span className="erix-text-primary erix-underline erix-decoration-dotted erix-underline-offset-2 erix-cursor-pointer">
                          browse
                        </span>
                      </p>
                      <p className="erix-text-xs erix-text-muted-foreground erix-mt-0.5">
                        Images, Videos, PDFs — up to {maxSize} MB each
                      </p>
                    </div>
                    <input
                      type="file"
                      accept="image/*,video/*,application/pdf"
                      multiple
                      onChange={handleUpload}
                      className="erix-absolute erix-inset-0 erix-cursor-pointer erix-opacity-0"
                    />
                  </>
                )}
              </div>

              {/* Gallery Header */}
              <div className="erix-flex erix-items-center erix-justify-between erix-border-b erix-border-border/40 erix-pb-2">
                <span className="erix-text-[11px] erix-font-bold erix-uppercase erix-tracking-widest erix-text-muted-foreground/80">
                  Media Library
                  {!loadingImages && images.length > 0 && (
                    <span className="erix-ml-2 erix-rounded-full erix-bg-muted erix-px-2 erix-py-0.5 erix-text-[9px] erix-font-bold erix-text-muted-foreground/80">
                      {images.length}
                    </span>
                  )}
                </span>
              </div>

              {/* Gallery */}
              {loadingImages ? (
                <div
                  className={cn(
                    viewMode === "grid"
                      ? "grid grid-cols-3 sm:grid-cols-4 gap-2"
                      : "space-y-1.5",
                  )}
                >
                  {[...Array(viewMode === "grid" ? 10 : 5)].map((_, i) =>
                    viewMode === "grid" ? (
                      <GridSkeleton key={i} />
                    ) : (
                      <ListSkeleton key={i} />
                    ),
                  )}
                </div>
              ) : filteredImages.length === 0 ? (
                <div className="erix-flex erix-flex-col erix-items-center erix-justify-center erix-py-20 erix-text-center">
                  <div className="erix-mb-4 erix-flex erix-h-16 erix-w-16 erix-items-center erix-justify-center erix-rounded-full erix-bg-muted/50 erix-border erix-border-border/50">
                    <Search className="erix-h-7 erix-w-7 erix-text-muted-foreground/40" />
                  </div>
                  <p className="erix-text-sm erix-font-semibold erix-text-foreground/80">
                    {searchQuery || filterType !== "all"
                      ? "No matching files"
                      : "Your library is empty"}
                  </p>
                  <p className="erix-mt-1.5 erix-text-xs erix-text-muted-foreground erix-max-w-[200px]">
                    {searchQuery || filterType !== "all"
                      ? "Try adjusting your search or filters to find what you're looking for."
                      : "Upload your first file to see it here in the library."}
                  </p>
                  {(searchQuery || filterType !== "all") && (
                    <Button
                      variant="link"
                      size="sm"
                      className="erix-mt-2 erix-text-primary"
                      onClick={() => {
                        setSearchQuery("");
                        setFilterType("all");
                      }}
                    >
                      Reset all filters
                    </Button>
                  )}
                </div>
              ) : (
                <div
                  className={cn(
                    viewMode === "grid"
                      ? "grid grid-cols-3 sm:grid-cols-4 gap-2"
                      : "space-y-1.5",
                  )}
                >
                  {/* Upload skeleton placeholders */}
                  {isUploading &&
                    [...Array(uploadingCount)].map((_, i) =>
                      viewMode === "grid" ? (
                        <GridSkeleton key={`up-${i}`} />
                      ) : (
                        <ListSkeleton key={`up-${i}`} />
                      ),
                    )}

                  {filteredImages.map((src, i) => {
                    const isDeleting =
                      src.key && deletingKeys.includes(src.key);
                    const selected = isSelected(src);
                    const displayName = getDisplayName(src);

                    if (isDeleting) {
                      return viewMode === "grid" ? (
                        <GridSkeleton key={src.key || i} />
                      ) : (
                        <ListSkeleton key={src.key || i} />
                      );
                    }

                    if (viewMode === "list") {
                      return (
                        <div
                          key={src.key || i}
                          onClick={() => handleSelectImage(src)}
                          className={cn(
                            "group flex cursor-pointer items-center gap-3 rounded-lg border p-2 transition-all duration-150",
                            selected
                              ? "border-primary/60 bg-primary/5 ring-1 ring-primary/30"
                              : "border-border/60 bg-background hover:border-border hover:bg-accent/40",
                          )}
                        >
                          {/* Thumb */}
                          <MediaThumb src={src} index={i} mode="list" />

                          {/* Info */}
                          <div className="erix-min-w-0 erix-flex-1">
                            <p
                              className="erix-text-xs erix-font-medium erix-leading-snug erix-text-foreground"
                              style={{ wordBreak: "break-word" }}
                              title={displayName}
                            >
                              {displayName || `Media ${i + 1}`}
                            </p>
                            <p className="erix-mt-0.5 erix-text-[10px] erix-text-muted-foreground">
                              {src.size ? formatBytes(src.size) : "—"}
                              {src.lastModified &&
                                ` · ${new Date(src.lastModified).toLocaleDateString()}`}
                            </p>
                          </div>

                          {/* Actions */}
                          <div className="erix-flex erix-shrink-0 erix-items-center erix-gap-1.5 erix-pr-1">
                            <button
                              onClick={(e) => handleDeleteMedia(e, src)}
                              className="erix-rounded-md erix-p-1 erix-text-muted-foreground erix-opacity-0 erix-transition-all hover:erix-bg-destructive/10 hover:erix-text-destructive group-hover:erix-opacity-100"
                              title="Delete"
                            >
                              <Trash2 className="erix-h-3.5 erix-w-3.5" />
                            </button>
                            <div
                              className={cn(
                                "flex h-5 w-5 items-center justify-center rounded-full border-2 transition-all",
                                selected
                                  ? "border-primary bg-primary text-primary-foreground"
                                  : "border-border bg-background group-hover:border-primary/50",
                              )}
                            >
                              {selected && (
                                <Check className="erix-h-3 erix-w-3" />
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    }

                    // Grid view
                    return (
                      <div
                        key={src.key || i}
                        onClick={() => handleSelectImage(src)}
                        className={cn(
                          "group relative cursor-pointer overflow-hidden rounded-lg border transition-all duration-150",
                          selected
                            ? "border-primary ring-2 ring-primary/40 ring-offset-1"
                            : "border-border/60 hover:border-primary/40",
                        )}
                      >
                        {/* Thumbnail */}
                        <MediaThumb src={src} index={i} mode="grid" />

                        {/* Hover overlay */}
                        <div
                          className={cn(
                            "absolute inset-0 bg-black/0 transition-colors duration-150 group-hover:bg-black/10",
                            selected && "bg-primary/10",
                          )}
                        />

                        {/* Delete button */}
                        <button
                          onClick={(e) => handleDeleteMedia(e, src)}
                          className="erix-absolute erix-top-1.5 erix-left-1.5 erix-z-10 erix-flex erix-h-6 erix-w-6 erix-items-center erix-justify-center erix-rounded-full erix-bg-black/60 erix-text-white erix-opacity-0 erix-shadow erix-backdrop-blur-sm erix-transition-all hover:erix-bg-red-500 group-hover:erix-opacity-100"
                          title="Delete"
                        >
                          <Trash2 className="erix-h-3 erix-w-3" />
                        </button>

                        {/* Selection badge */}
                        <div
                          className={cn(
                            "absolute top-1.5 right-1.5 z-10 flex h-5 w-5 items-center justify-center rounded-full border-2 transition-all",
                            selected
                              ? "border-primary bg-primary text-white shadow"
                              : "border-white/70 bg-black/30 backdrop-blur-sm opacity-0 group-hover:opacity-100",
                          )}
                        >
                          {selected && <Check className="erix-h-3 erix-w-3" />}
                        </div>

                        {/* Filename label */}
                        <div className="erix-border-t erix-border-border/50 erix-bg-background/95 erix-px-2 erix-py-1">
                          <p
                            className="erix-text-[9px] erix-font-medium erix-text-muted-foreground"
                            style={{
                              wordBreak: "break-word",
                              lineHeight: "1.2",
                            }}
                            title={displayName}
                          >
                            {displayName || `Media ${i + 1}`}
                          </p>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* ── Footer ── */}
            <div className="erix-shrink-0 erix-border-t erix-border-border/60 erix-bg-background erix-px-5 erix-py-3">
              <div className="erix-flex erix-items-center erix-justify-between erix-gap-3">
                {/* Selection status */}
                <span className="erix-text-xs erix-text-muted-foreground">
                  {selCount > 0 ? (
                    <span className="erix-flex erix-items-center erix-gap-1.5 erix-font-medium erix-text-foreground">
                      <div className="erix-flex erix-h-4 erix-w-4 erix-items-center erix-justify-center erix-rounded-full erix-bg-primary erix-text-white">
                        <Check className="erix-h-2.5 erix-w-2.5" />
                      </div>
                      {selCount} selected
                    </span>
                  ) : (
                    "No files selected"
                  )}
                </span>

                <div className="erix-flex erix-items-center erix-gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    className="erix-h-8 erix-px-4 erix-text-xs"
                    onClick={() => {
                      handleOpenChange(false);
                      setSelectedImage([]);
                    }}
                  >
                    Cancel
                  </Button>
                  <Button
                    size="sm"
                    variant="primary"
                    disabled={!selCount || isUploading}
                    onClick={() => {
                      onInsert?.(selectedImages!);
                      handleOpenChange(false);
                      setSelectedImage([]);
                    }}
                    className="erix-h-8 erix-gap-1.5 erix-px-5 erix-text-xs"
                  >
                    {isUploading ? (
                      <>
                        <Loader2 className="erix-h-3.5 erix-w-3.5 erix-animate-spin" />
                        Uploading…
                      </>
                    ) : (
                      <>
                        <Check className="erix-h-3.5 erix-w-3.5" />
                        {selCount > 0
                          ? `Use ${selCount} file${selCount > 1 ? "s" : ""}`
                          : "Select"}
                      </>
                    )}
                  </Button>
                </div>
              </div>
            </div>
          </TabsContent>

          {variant === "richtext" && (
            <TabsContent
              value="url"
              className="erix-mt-0 erix-flex-1 erix-flex erix-flex-col erix-data-[state=inactive]:erix-hidden"
            >
              <div className="erix-flex-1 erix-p-5 erix-flex erix-flex-col erix-gap-4">
                <div className="erix-space-y-1">
                  <h3 className="erix-text-sm erix-font-medium erix-leading-none">
                    Insert via External URL
                  </h3>
                  <p className="erix-text-[13px] erix-text-muted-foreground erix-leading-relaxed">
                    Provide a direct link to an image file. We recommend using
                    HTTPS URLs.
                  </p>
                </div>
                <div className="erix-flex erix-items-center erix-gap-2">
                  <Input
                    className="erix-h-9"
                    placeholder="https://example.com/image.png"
                    value={externalUrl}
                    onChange={(e) => setExternalUrl(e.target.value)}
                  />
                  <Button
                    size="sm"
                    variant="primary"
                    className="erix-h-9 erix-px-4 erix-shrink-0"
                    onClick={() => {
                      onInsert?.([{ url: externalUrl } as ImageFormat]);
                      handleOpenChange(false);
                      setExternalUrl("");
                    }}
                    disabled={!externalUrl}
                  >
                    <LinkIcon className="erix-w-3.5 erix-h-3.5 erix-mr-1.5" />
                    Insert URL
                  </Button>
                </div>
              </div>
            </TabsContent>
          )}
        </Tabs>
      </DialogContent>
    </Dialog>
  );
};
